<a href="https://colab.research.google.com/github/TanyaratJivnot/DataAnalytics/blob/main/Data_Analytic(Tanyarat).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Data

In [35]:
!pip install pymongo dnspython
!pip install streamlit
from pymongo import MongoClient
from datetime import datetime
import pandas as pd

URI = 'mongodb+srv://botnoivoice:Botnoi1!@cluster0.1jgbr.mongodb.net/admin?retryWrites=true&w=majority'
client = MongoClient(URI)
database = client['prod-tts-payment']

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pymongo in /usr/local/lib/python3.10/dist-packages (4.3.3)
Requirement already satisfied: dnspython in /usr/local/lib/python3.10/dist-packages (2.3.0)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: streamlit in /usr/local/lib/python3.10/dist-packages (1.23.1)
Requirement already satisfied: altair<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.2.2)
Requirement already satisfied: blinker<2,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (1.6.2)
Requirement already satisfied: cachetools<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (5.3.0)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (8.1.3)
Requirement already satisfied: importlib-metadata<7,>=1.4 in /usr/local/lib/python3.10/dist-packages (from streamlit) (6.6.0)
Requirement already satisfied: numpy<2,>=1 in /usr/local/lib/python3.10/dist-packages (from streamlit) (1.22.4)
Requirement already satisfied: packaging<24,>=14.1 in /usr/local/lib/python3.10/dist-packages (from streamlit) (23.1)
Requirement already satisfied: pandas<3,>=0.25 in /usr/local/lib/python3.10/dist-packages (from streamlit) (1.5.3)
Requirement already satisfied: pillow<10,>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (8.4.0)
Requirement already satisfied: protobuf<5,>=3.20 in /usr/local/lib/python3.10/dist-packages (from streamlit) (3.20.3)
Requirement already satisfied: pyarrow>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (9.0.0)
Requirement already satisfied: pympler<2,>=0.9 in /usr/local/lib/python3.10/dist-packages (from streamlit) (1.0.1)
Requirement already satisfied: python-dateutil<3,>=2 in /usr/local/lib/python3.10/dist-packages (from streamlit) (2.8.2)
Requirement already satisfied: requests<3,>=2.4 in /usr/local/lib/python3.10/dist-packages (from streamlit) (2.27.1)
Requirement already satisfied: rich<14,>=10.11.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (13.3.4)
Requirement already satisfied: tenacity<9,>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (8.2.2)
Requirement already satisfied: toml<2 in /usr/local/lib/python3.10/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.0.1 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.5.0)
Requirement already satisfied: tzlocal<5,>=1.1 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.3)
Requirement already satisfied: validators<1,>=0.2 in /usr/local/lib/python3.10/dist-packages (from streamlit) (0.20.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3 in /usr/local/lib/python3.10/dist-packages (from streamlit) (3.1.31)
Requirement already satisfied: pydeck<1,>=0.1.dev5 in /usr/local/lib/python3.10/dist-packages (from streamlit) (0.8.1b0)
Requirement already satisfied: tornado<7,>=6.0.3 in /usr/local/lib/python3.10/dist-packages (from streamlit) (6.3.1)
Requirement already satisfied: watchdog in /usr/local/lib/python3.10/dist-packages (from streamlit) (3.0.0)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (0.4)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (3.1.2)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (4.3.3)
Requirement already satisfied: toolz in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (0.12.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.10/dist-packages (from gitpython!=3.1.19,<4,>=3->streamlit) (4.0.10)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata<7,>=1.4->streamlit) (3.15.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=0.25->streamlit) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil<3,>=2->streamlit) (1.16.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.4->streamlit) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.4->streamlit) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.4->streamlit) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.4->streamlit) (3.4)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.11.0->streamlit) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.11.0->streamlit) (2.14.0)
Requirement already satisfied: pytz-deprecation-shim in /usr/local/lib/python3.10/dist-packages (from tzlocal<5,>=1.1->streamlit) (0.1.0.post0)
Requirement already satisfied: decorator>=3.4.0 in /usr/local/lib/python3.10/dist-packages (from validators<1,>=0.2->streamlit) (4.4.2)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3->streamlit) (5.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.2)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.1.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.19.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py<3.0.0,>=2.2.0->rich<14,>=10.11.0->streamlit) (0.1.2)
Requirement already satisfied: tzdata in /usr/local/lib/python3.10/dist-packages (from pytz-deprecation-shim->tzlocal<5,>=1.1->streamlit) (2023.3)

In [36]:
import pandas as pd
import matplotlib.pyplot as plt
import streamlit as st
# %matplotlib inline
%config InlineBackend.figure_format = 'svg' # Plot image with vector
pd.set_option('display.float_format','{:,.2f} '.format)
import seaborn as sns
import numpy as np

%matplotlib inline
# ติดตั้งฟ้อนภาษาไทย
!wget -q https://github.com/Phonbopit/sarabun-webfont/raw/master/fonts/thsarabunnew-webfont.ttf
# !pip install -U --pre matplotlib  
import matplotlib as mpl
mpl.font_manager.fontManager.addfont('thsarabunnew-webfont.ttf')
mpl.rc('font', family='TH Sarabun New')
import warnings
warnings.filterwarnings("ignore")

In [37]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [38]:
documents = database.list_collection_names()
df = pd.DataFrame(documents)

df

                             0
0                     progress
1                        share
2                      coupons
3            use_invite_coupon
4                 voice_studio
5                     feedback
6         logs_error_get_voice
7   transfer_credits_statement
8          sales_withdraw_logs
9                     max_size
10                   blacklist
11                device_check
12                  dictionary
13           sound_sample_logs
14               alert_message
15               history_point
16            transfer_credits
17                pay_database
18                     speaker
19         generate_voice_link
20              logs_agreement
21                    aws_logs
22                       users
23                   whitelist
24                     package
25                      record
26                    sessions
27                     payment
28                  sales_data
29                 use_coupons
30                      gotest
31                temp_storage
32               invite_coupon
33                 aws_message
34                        logs
35               personal_form
36                     storage
37                     message

# Looking Data Download

## message Data

In [39]:
# ดึง data ตั้งแต่ 2022-11-01 ถึง 20xx-xx-xx
message = pd.DataFrame(list(database['message'].find( { 'datetime': {"$gt":"2023-05-01","$lt":"2023-05-02" }})))

In [40]:
message.head(5)

,_id,user_id,message,channel,count,speaker,datetime,url
0,644e9e94f01730129865d70d,MCQ02KQyogcHRiZCTRpbwOE0e8K2,สัมผัสกลิ่นรส หลงไหลความเข้มข้นของกาแฟดำ คงควา...,play,147,pla,2023-05-01 00:00:04,NaN
1,644e9e94a30ecd41c05556d0,h9O0P8nZDrdiE4VK1vge8hvzUqj1,อาวุธปืนสั้น 9 มม. Sigsauer M 1 8 จำนวน 20 กระ...,play,90,nopchai,2023-05-01 00:00:04,NaN
2,644e9e9a5ed4b2ab6a739cf6,BAwiGrCO5dVrqALmjhj00YGU4uz1,ชีวิตติดรำ by Grace ny,play,19,nopchai,2023-05-01 00:00:10,NaN
3,644e9e9f7102cdfd92d6c4fd,U908a60196596b4bfebcb7fe49d72d6dd,องค์ประกอบที่2ด้านการปฏิบัติงาน1การจัดการเรียน...,play,222,tonkhaow,2023-05-01 00:00:15,NaN
4,644e9e9f4ef3bbfbc23a0d31,U65b08576ca15de0446856dc316ca9d8b,ให้ตั้งนะโม3จบ แล้วกล่าวคำว่า,play,28,nid,2023-05-01 00:00:15,NaN

In [41]:
message.columns

Index(['_id', 'user_id', 'message', 'channel', 'count', 'speaker', 'datetime',
       'url'],
      dtype='object')

In [42]:
message.shape

(18896, 8)

In [43]:
len(message)

18896

In [44]:
message.isna().sum()

_id             0
user_id         0
message         0
channel         0
count           0
speaker         0
datetime        0
url         18715
dtype: int64

## users data

In [45]:
users = pd.DataFrame(list(database['users'].find()))

In [46]:
users.head(5)

,_id,user_id,username,email,image,jwt,start_datetime,end_datetime,credits,invite_code,...,agreement,personal_form,uid,account_status,last_login_type,subscription,play_quota,platform,sale_code_name,remember_password
0,613f706c082b44d43f4f81e5,U81901d7bdb0831777bfe3b5dfdeaadd7,Bee.kmutnb🌻,beeminecraft@gmail.com,https://profile.line-scdn.net/0hZRlOiOe8BX1RNh...,eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiO...,2021-09-13 15:38:20.384,2021-09-13 15:56:28.785,900.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6140a91d082b44d43f4f81e7,U682311b2261c43c35d9cfb4c0040d20b,mig kasidis,wizhahe_dv_vb@hotmail.com,https://profile.line-scdn.net/0hUvgAN1urCllaOB...,eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiO...,2021-09-14 13:52:29.205,2023-04-25 02:52:28.084,"19,449.00",True,...,True,True,029e5256-155f-5772-a398-c0ea652b8514,old user,NaN,NaN,NaN,NaN,NaN,NaN
2,6140bc51082b44d43f4f81ea,U493b213bf06fc60917bb17434581c384,Qkuton,olindion@hotmail.com,https://profile.line-scdn.net/0h0RjtbG9fb31XDX...,eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiO...,2021-09-14 15:14:25.754,2022-04-21 09:12:07.464,"39,935.00",False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,61416b24fab439ae592bfc44,Ud0459a4310e6c7705f7424da1d15dadb,Pattanun [Arm],phattanun19@hotmail.com,https://profile.line-scdn.net/0hBW_oHTWQHXhiFg...,eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiO...,2021-09-15 03:40:20.509,2023-05-24 02:22:28.374,"24,874.00",True,...,True,False,cc379d3f-2204-58c9-804d-1497ef908391,old user,line,NaN,NaN,NaN,NaN,NaN
4,61469c87fab439ae592bfc46,U4c0eca7d983f06a926806d2c02ffd48f,P R A N,prandd.cnx@gmail.com,https://profile.line-scdn.net/0hxrhE4zZoJ11VPD...,eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiO...,2021-09-19 02:12:23.186,2022-07-22 07:54:06.197,9.00,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
users.columns

Index(['_id', 'user_id', 'username', 'email', 'image', 'jwt', 'start_datetime',
       'end_datetime', 'credits', 'invite_code', 'token', 'sign_in_provider',
       'agreement', 'personal_form', 'uid', 'account_status',
       'last_login_type', 'subscription', 'play_quota', 'platform',
       'sale_code_name', 'remember_password'],
      dtype='object')

In [48]:
users.shape

(1331118, 22)

In [49]:
users.isna().sum()

_id                        0
user_id                    0
username                   5
email                      0
image                      0
jwt                        0
start_datetime             0
end_datetime               0
credits                    0
invite_code              567
token                1305466
sign_in_provider      977674
agreement             957090
personal_form        1100568
uid                  1100568
account_status       1100568
last_login_type       873388
subscription         1280212
play_quota           1280212
platform              898858
sale_code_name       1331099
remember_password    1331118
dtype: int64

## payment Data

In [50]:
#get all data
payment = pd.DataFrame(list(database['payment'].find()))

In [51]:
payment = pd.DataFrame(list(database['payment']
                            .find({'datetime': {"$gt":"2023-02-01","$lt":"2023-03-22" }})))

In [52]:
payment.tail(4)

,_id,user_id,package_id,point,price,promotion,qrcode,transactionid,datetime,actual_time,ref1,status,sale_code_name
45192,641a41262d56e125be1a6b70,U033d6cdd40930ae3faa3ac8692f4f782,credits,115,2,0,00020101021230820016A0000006770101120115010753...,0107536000374040000022030012434300012523032206...,2023-03-21 23:43:34,2023-03-21 23:43:34.082,TTS-4XKOPKDG7FS396BW,True,NaN
45193,641a414ecf58e28c4fbd3a46,U4ce90321a5f3c13b927ccd5d4ed79835,package_100,5000,100,400,00020101021230820016A0000006770101120115010753...,0107536000374040000022030012434300012523032206...,2023-03-21 23:44:14,2023-03-21 23:44:14.082,TTS-J0L7K0HXJL79LT28,True,NaN
45194,641a420cccaf5bf2368c134c,U5e07dd7cde8b53d0c6bd171071cf3621,credits,111,2,0,00020101021230820016A0000006770101120115010753...,0107536000374040000022030012434300012523032206...,2023-03-21 23:47:24,2023-03-21 23:47:24.577,TTS-I8Z6P8ZDIWPBKNHO,True,NaN
45195,641a43243fe69660b964ed8a,U5e07dd7cde8b53d0c6bd171071cf3621,credits,140,2,0,00020101021230820016A0000006770101120115010753...,0107536000374040000022030012434300012523032206...,2023-03-21 23:52:04,2023-03-21 23:52:04.825,TTS-Q5LSWOK9CSV6DSIE,True,NaN

## speaker Data

In [53]:
speaker = pd.DataFrame(list(database['speaker'].find()))

In [54]:
speaker.drop(columns = ['image','face_image','horizontal_face_image','square_image','audio']).head(3)

,_id,speaker_id,speaker_name,eng_name,thai_name,voice_style,age_style,speech_style,speed,popularity,type,language,status,gender,private,allow_uid
0,62e17c8fa082c5442d496a9a,6,pla,Siren,ไซเรน,"[เสียงตื่นเต้น, เสียงมั่นใจ]",วัยรุ่น,"[สไตล์เล่าเรื่อง, สไตล์ตัวละคร]",พูดเร็ว,ยอดนิยม,0,TH,True,ผู้หญิง,NaN,NaN
1,62e17c8fa082c5442d496a9b,8,ati,Alisa,อลิสา,[เสียงน่ารัก],วัยรุ่น,"[สไตล์เล่าเรื่อง, สไตล์บรรยาย]",พูดกลาง,-,1,TH,True,ผู้หญิง,NaN,NaN
2,62e17c8fa082c5442d496a9c,9,max,Leo,เลโอ,"[เสียงตื่นเต้น, เสียงมั่นใจ]",วัยผู้ใหญ่,"[สไตล์อ่านข่าว, สไตล์สปอตโฆษณา]",พูดเร็ว,-,1,TH,True,ผู้ชาย,NaN,NaN

## coupons Data

In [55]:
coupons = pd.DataFrame(list(database['coupons'].find()))

In [56]:
coupons.head(3)

,_id,coupon_name,point,minimum,start_time,uses,timestamp
0,6139d4182feb7522f4b0f557,TWENTY,20,0,2021-09-30 23:19:13,0,NaN
1,618ddb117bf6faeb7d823326,BNVWORKSHOP,2500,0,2021-09-30 23:19:13,0,NaN
2,613b080719f9bf0aa299cb5a,BOTNOIPOINT500,500,0,2021-09-30 23:19:13,0,NaN

## Save to GG Drive

In [57]:
message.to_pickle('/content/drive/MyDrive/Botnoi/data/message_2023.png')

In [58]:
users.to_pickle('/content/drive/MyDrive/Botnoi/data/user.p')

In [59]:
payment.to_pickle('/content/drive/MyDrive/Botnoi/data/payments_df.p')

In [60]:
speaker.to_pickle('/content/drive/MyDrive/Botnoi/data/speaker_df.p')

# ตั้งคำถามเเละสมมุติฐาน

# Streamlit

In [61]:
!pip install streamlit
import streamlit as st

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: streamlit in /usr/local/lib/python3.10/dist-packages (1.23.1)
Requirement already satisfied: altair<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.2.2)
Requirement already satisfied: blinker<2,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (1.6.2)
Requirement already satisfied: cachetools<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (5.3.0)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (8.1.3)
Requirement already satisfied: importlib-metadata<7,>=1.4 in /usr/local/lib/python3.10/dist-packages (from streamlit) (6.6.0)
Requirement already satisfied: numpy<2,>=1 in /usr/local/lib/python3.10/dist-packages (from streamlit) (1.22.4)
Requirement already satisfied: packaging<24,>=14.1 in /usr/local/lib/python3.10/dist-packages (from streamlit) (23.1)
Requirement already satisfied: pandas<3,>=0.25 in /usr/local/lib/python3.10/dist-packages (from streamlit) (1.5.3)
Requirement already satisfied: pillow<10,>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (8.4.0)
Requirement already satisfied: protobuf<5,>=3.20 in /usr/local/lib/python3.10/dist-packages (from streamlit) (3.20.3)
Requirement already satisfied: pyarrow>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (9.0.0)
Requirement already satisfied: pympler<2,>=0.9 in /usr/local/lib/python3.10/dist-packages (from streamlit) (1.0.1)
Requirement already satisfied: python-dateutil<3,>=2 in /usr/local/lib/python3.10/dist-packages (from streamlit) (2.8.2)
Requirement already satisfied: requests<3,>=2.4 in /usr/local/lib/python3.10/dist-packages (from streamlit) (2.27.1)
Requirement already satisfied: rich<14,>=10.11.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (13.3.4)
Requirement already satisfied: tenacity<9,>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (8.2.2)
Requirement already satisfied: toml<2 in /usr/local/lib/python3.10/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.0.1 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.5.0)
Requirement already satisfied: tzlocal<5,>=1.1 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.3)
Requirement already satisfied: validators<1,>=0.2 in /usr/local/lib/python3.10/dist-packages (from streamlit) (0.20.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3 in /usr/local/lib/python3.10/dist-packages (from streamlit) (3.1.31)
Requirement already satisfied: pydeck<1,>=0.1.dev5 in /usr/local/lib/python3.10/dist-packages (from streamlit) (0.8.1b0)
Requirement already satisfied: tornado<7,>=6.0.3 in /usr/local/lib/python3.10/dist-packages (from streamlit) (6.3.1)
Requirement already satisfied: watchdog in /usr/local/lib/python3.10/dist-packages (from streamlit) (3.0.0)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (0.4)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (3.1.2)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (4.3.3)
Requirement already satisfied: toolz in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (0.12.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.10/dist-packages (from gitpython!=3.1.19,<4,>=3->streamlit) (4.0.10)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata<7,>=1.4->streamlit) (3.15.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=0.25->streamlit) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil<3,>=2->streamlit) (1.16.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.4->streamlit) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.4->streamlit) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.4->streamlit) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.4->streamlit) (3.4)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.11.0->streamlit) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.11.0->streamlit) (2.14.0)
Requirement already satisfied: pytz-deprecation-shim in /usr/local/lib/python3.10/dist-packages (from tzlocal<5,>=1.1->streamlit) (0.1.0.post0)
Requirement already satisfied: decorator>=3.4.0 in /usr/local/lib/python3.10/dist-packages (from validators<1,>=0.2->streamlit) (4.4.2)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3->streamlit) (5.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.2)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.1.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.19.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py<3.0.0,>=2.2.0->rich<14,>=10.11.0->streamlit) (0.1.2)
Requirement already satisfied: tzdata in /usr/local/lib/python3.10/dist-packages (from pytz-deprecation-shim->tzlocal<5,>=1.1->streamlit) (2023.3)